name: ghp-publish

on:
  push:
    branches: [ master ]
    tags-ignore: [ '*' ]
  workflow_dispatch:

jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Submodule update
        run: git submodule update --init --recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Pull container
        run: docker pull kairi003/bsdiff-wasm-build:latest

      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        run: npm run build:release
      
      - run: ls -l docs
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
