name: ghp-publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-build-workflow:
    uses: ./.github/workflows/build-package.yml

  publish-pages:
    needs: call-build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bsdiff-wasm-dist
          path: dist
      
      - run: ls -l docs
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
